Enable xa-transaction
ballerina-platform/module-ballerinax-mssql pull request #467
Opened 2022-11-10 15:34 UTC by kalaiyarasiganeshalingam

## Purpose
$Subject

## Examples

## Checklist
- [ ] Linked to an issue
- [ ] Updated the specification
- [ ] Updated the changelog
- [ ] Added tests
- [ ] Checked native-image compatibility

2022-11-11 07:01 UTC, daneshk commented
@kalaiyarasiganeshalingam don't we need an additional docker image with XA transaction enabled for testing?

2022-11-11 07:11 UTC, niveathika commented on ballerina/Client.bal
> +    boolean useXADatasource = false;
Where is this processed?

2022-11-11 07:11 UTC, niveathika requested changes
`useXADatasource` is not processed

2022-11-13 14:10 UTC, daneshk commented on ballerina/tests/resources/Dockerfile
> +FROM mcr.microsoft.com/mssql/server:2017-latest
why we downgrade the server?

2022-11-15 10:19 UTC, closed without merging